### ISSUE TITLE
undefined function imagecreatefrompng() - MediaWiki 1.39.6

### ISSUE THREAD

**Issue by m3w88** [nbdd0121/MW-Avatar#15]
OS: Ubuntu 20.04
PHP 7.4
MediaWiki 1.39.6

**LocalSetting.php configuration**
wfLoadExtension('Avatar');
$wgEnableUploads = true;
$wgGroupPermissions["*"]["upload"] = true;
$wgGroupPermissions["*"]["avatarupload"] = true;
$wgGroupPermissions["sysop"]["avataradmin"] = true;

Notes:
- I did install the required php-gd dependency 

Error: Call to undefined function Avatar\imagecreatefrompng()
Backtrace:
from /var/www/html/w/extensions/Avatar/Thumbnail.php(20)
#0 /var/www/html/w/extensions/Avatar/Thumbnail.php(29): Avatar\Thumbnail->__construct()
#1 /var/www/html/w/extensions/Avatar/SpecialUpload.php(53): Avatar\Thumbnail::open()
#2 /var/www/html/w/extensions/Avatar/SpecialUpload.php(32): Avatar\SpecialUpload->processUpload()
#3 /var/www/html/w/includes/specialpage/SpecialPage.php(701): Avatar\SpecialUpload->execute()
#4 /var/www/html/w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#5 /var/www/html/w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#6 /var/www/html/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#7 /var/www/html/w/includes/MediaWiki.php(562): MediaWiki->main()
#8 /var/www/html/w/index.php(50): MediaWiki->run()
#9 /var/www/html/w/index.php(46): wfIndexMain()
#10 {main}

**Comment by nbdd0121** [comment]
Could you share your phpinfo?
